#import turtle

# turtle.shape('turtle')# turtle   arrow    circle 
# turtle.shapesize(4)
# turtle.color("green")
# turtle.pencolor("brown")
# turtle.pensize(7)
# turtle.fillcolor("red")
# turtle.begin_fill()
# turtle.forward(100)
# turtle.left(90)
# turtle.forward(100)
# turtle.left(90)
# turtle.forward(100)
# turtle.left(90)
# turtle.forward(100)
# turtle.left(90)
# turtle.end_fill()
# turtle.color("green")
# turtle.done()